av_ncfiles = ["C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ljh_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ljh_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ljp_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ljp_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ljc_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ljc_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ltc_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ltc_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_lth_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_lth_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ltp_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_ltp_2007-2008_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_sth_2006-2007_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_sth_2007-2008_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_stc_2006-2007_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_stc_2007-2008_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_sjc_2006-2007_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_sjc_2007-2008_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_sjp_2006-2007_senatorVariableDecayRate_1.nc",
#              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/sa_sa2_vars/sa_sa2_sjp_2007-2008_senatorVariableDecayRate_1.nc"
              ]#