#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1110.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1120.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1130.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1210.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1220.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1230.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1310.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1320.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj1330.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2110.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2120.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2130.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2210.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2220.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2230.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2310.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2320.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lj2330.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1110.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1120.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1130.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1210.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1220.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1230.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1310.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1320.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj1330.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2110.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2120.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2130.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2210.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2220.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2230.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2310.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2320.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mj2330.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1110.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1120.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1130.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1210.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1220.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1230.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1310.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1320.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj1330.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2110.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2120.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2130.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2210.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2220.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2230.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2310.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2320.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sj2330.txt
#
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1111.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1112.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1113.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1121.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1122.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1123.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1131.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1132.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1133.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1211.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1212.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1213.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1221.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1222.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1223.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1231.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1232.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1233.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1311.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1312.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1313.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1321.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1322.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1323.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1331.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1332.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc1333.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2111.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2112.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2113.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2121.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2122.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2123.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2131.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2132.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2133.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2211.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2212.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2213.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2221.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2222.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2223.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2231.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2232.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2233.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2311.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2312.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2313.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2321.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2322.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2323.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2331.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2332.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_lc2333.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1111.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1112.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1113.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1121.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1122.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1123.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1131.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1132.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1133.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1211.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1212.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1213.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1221.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1222.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1223.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1231.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1232.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1233.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1311.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1312.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1313.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1321.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1322.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1323.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1331.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1332.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc1333.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2111.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2112.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2113.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2121.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2122.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2123.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2131.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2132.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2133.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2211.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2212.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2213.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2221.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2222.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2223.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2231.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2232.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2233.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2311.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2312.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2313.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2321.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2322.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2323.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2331.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2332.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_mc2333.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1111.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1112.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1113.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1121.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1122.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1123.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1131.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1132.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1133.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1211.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1212.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1213.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1221.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1222.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1223.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1231.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1232.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1233.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1311.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1312.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1313.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1321.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1322.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1323.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1331.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1332.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc1333.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2111.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2112.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2113.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2121.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2122.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2123.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2131.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2132.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2133.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2211.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2212.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2213.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2221.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2222.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2223.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2231.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2232.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2233.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2311.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2312.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2313.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2321.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2322.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2323.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2331.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2332.txt
#docker run -v ${DISK_MAPPING} ${SUMMA_EXE} -p never -s _senatorVariableDecayRate  -m /summaTestCases_2.x/settings/wrrPaperTestCases/swampAngel/filemanager/summa_fileManager_swampAngel_sa2_sc2333.txt







import os
from os import listdir
for fileName in os.listdir("."):
    os.rename(fileName, fileName.replace("1 - Copy", "3"))