av_ncfiles = ["C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_lai1_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_lai1_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_ce2_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_ce2_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_lai2_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_lai2_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_si2_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_si2_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr2_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr2_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr3_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr3_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr4_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr4_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr5_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_swr5_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_vr2_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_vr2_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_vr3_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_vr3_2007-2008_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_wp2_2006-2007_senatorVariableDecayRate_1.nc",
              "C:/Users/HHS/summaTestCases_2.x/output/swampAngel/vegTest_wp2_2007-2008_senatorVariableDecayRate_1.nc"]

